---
version: 2.1

executors:
  php_56_node:
    docker:
      - image: circleci/php:5.6-cli-node
  xcode_10_3:
    macos:
      xcode: '10.3.0'
    environment:
      BUNDLE_PATH: ~/bundler

jobs:
  setup:
    executor: php_56_node
    steps:
      - checkout
      # Composer
      - restore_cache:
          keys:
            - composer-cache-v1-{{ .Branch }}-{{ checksum "composer.lock" }}
            - composer-cache-v1-{{ .Branch }}-
            - composer-cache-v1-
      - run:
          name: Installing composer dependencies
          command: composer install
      - save_cache:
          key: composer-cache-v1-{{ .Branch }}-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # npm
      - restore_cache:
          keys:
            - npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-v1-{{ .Branch }}-
            - npm-cache-v1-
      - run:
          name: Installing npm dependencies
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  lint_javascript:
    executor: php_56_node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Linting JavaScript using ESLint
          command: npm run eslint

  lint_php:
    executor: php_56_node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Linting PHP syntax
          command: composer phplint
      - run:
          name: Linting PHP using PHP_CodeSniffer
          command: composer phpcs

  lint_structured_files:
    executor: php_56_node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Linting structured files using Prettier
          command: npm run lint-structured-files

  lint_swift:
    executor: xcode_10_3
    steps:
      - checkout
      # Bundler
      - restore_cache:
          keys:
            - bundler-cache-v1-{{ .Branch }}-{{ checksum "./swift/TestRunner/Gemfile.lock" }}
            - bundler-cache-v1-{{ .Branch }}-
            - bundler-cache-v1-
      - run:
          name: Installing bundler dependencies
          command: cd "./swift/TestRunner" && bundle install --jobs=4 --retry=3
      - save_cache:
          key: bundler-cache-v1-{{ .Branch }}-{{ checksum "./swift/TestRunner/Gemfile.lock" }}
          paths:
            - $BUNDLE_PATH
      # CocoaPods
      - run:
          name: Using CircleCI CocoaPods mirror
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Seting up working directory
          command: cd "./swift/TestRunner" && bundle exec pod install
      # SwiftLint
      - run:
          name: Linting Swift using SwiftLint
          command: ./swift/TestRunner/Pods/SwiftLint/swiftlint lint --config swiftlint.yml "./swift"

workflows:
  version: 2

  git_push:
    jobs:
      - setup
      - lint_javascript:
          requires:
            - setup
      - lint_php:
          requires:
            - setup
      - lint_structured_files:
          requires:
            - setup
      - lint_swift

experimental:
  notify:
    branches:
      only:
        - master
